[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''

(
 /(
       \.eggs         # exclude a few common directories in the
	       | \.git          # root of the project
		       | \.hg
			       | \.mypy_cache
				       | \.tox
					       | \.venv
						       | _build
							       | buck-out
								       | build
									       | dist

  )/
    | foo.py           # also separately exclude a file named foo.py in
	                     # the root of the project

)
'''
[flake8]
max-line-length = 88

[isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[pylint]
max-line-length = 88
